baseurl = "https://floriank.github.io/"
title = "Notes of an awful developer"
contentdir = "content"
publishdir = "public"
canonifyurls = true
copyright = "(c) 2025 Florian Kraft"
theme = "nofancy"
[author]
  name = "Florian Kraft"
  github = "floriank"
  twitter = "carhillion"
  linkedin = "floriankraft"
  stackoverflow = "498226/florian"

[indices]
  category= "categories"

